# -*-coding: utf-8 -*-
from . import hr_payslip
from . import hr_contract
from . import primes
from . import categorie_salariale
from . import echelon_salariale
from . import grille_salaire
from . import hr_contract_type
from . import banque
from . import hr_employee
from . import hr_department
from . import res_company
from . import hr_payslip_run
from . import hr_config_settings
from . import hr_salary_rule
from . import centre_rh
